import { Container } from "@/components/ui/Container";
import { PageHeader } from "@/components/ui/PageHeader";
import { createMetadata } from "@/lib/metadata";
import { siteConfig } from "@/lib/constants";

export const metadata = createMetadata({
  title: "Terms of Service",
  description:
    "Rivit Terms of Service. Read the terms and conditions governing your use of Rivit's platform and services.",
  path: "/terms",
});

const sections = [
  {
    title: "Acceptance of Terms",
    content: `By accessing or using Rivit's website, mobile application, or services, you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use our services.`,
  },
  {
    title: "Description of Service",
    content: `Rivit provides AI-powered software planning and build orchestration tools that help users create product plans, execution roadmaps, and exportable build packs for AI coding environments. We reserve the right to modify, suspend, or discontinue any aspect of the service at any time.`,
  },
  {
    title: "Account Registration",
    content: `To access certain features, you may need to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information during registration.`,
  },
  {
    title: "Acceptable Use",
    content: `You agree not to use Rivit for any unlawful purpose, to violate any applicable laws or regulations, to infringe on the intellectual property rights of others, to transmit malicious code, or to attempt to gain unauthorized access to our systems or other users' accounts.`,
  },
  {
    title: "Intellectual Property",
    content: `Rivit and its original content, features, and functionality are owned by Rivit and are protected by international copyright, trademark, and other intellectual property laws. You retain ownership of the content and project data you create using our platform.`,
  },
  {
    title: "AI-Generated Content",
    content: `Plans, recommendations, and other outputs generated by Rivit's AI systems are provided for informational and planning purposes. You are solely responsible for reviewing, validating, and implementing any AI-generated content. Rivit does not guarantee the accuracy, completeness, or suitability of AI outputs for your specific use case.`,
  },
  {
    title: "Subscription and Payment",
    content: `Certain features require a paid subscription. By subscribing, you agree to pay all applicable fees. Subscriptions automatically renew unless cancelled before the renewal date. Refunds are handled in accordance with our refund policy and applicable app store terms.`,
  },
  {
    title: "Limitation of Liability",
    content: `To the maximum extent permitted by law, Rivit shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of our services. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim.`,
  },
  {
    title: "Disclaimer of Warranties",
    content: `Rivit is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or free of harmful components.`,
  },
  {
    title: "Termination",
    content: `We may terminate or suspend your account and access to Rivit at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties. Upon termination, your right to use the service ceases immediately.`,
  },
  {
    title: "Governing Law",
    content: `These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles. Any disputes arising from these Terms shall be resolved through binding arbitration or in the courts of competent jurisdiction.`,
  },
  {
    title: "Contact",
    content: `For questions about these Terms of Service, please contact us at ${siteConfig.contactEmail}.`,
  },
];

export default function TermsPage() {
  return (
    <>
      <PageHeader
        title="Terms of Service"
        description="Last updated: June 14, 2026"
      />

      <section className="py-16 sm:py-20">
        <Container>
          <div className="mx-auto max-w-3xl">
            <p className="text-sm leading-relaxed text-slate-400">
              Please read these Terms of Service carefully before using{" "}
              {siteConfig.name}. These terms govern your access to and use of
              our platform, mobile application, and related services.
            </p>

            <div className="mt-12 space-y-10">
              {sections.map((section) => (
                <div key={section.title}>
                  <h2 className="text-lg font-semibold text-white">
                    {section.title}
                  </h2>
                  <p className="mt-3 text-sm leading-relaxed text-slate-400">
                    {section.content}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </Container>
      </section>
    </>
  );
}
